// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Taqui.Database;

#nullable disable

namespace Taqui.Database.Migrations
{
    [DbContext(typeof(FIAPDBContext))]
    [Migration("20240913190448_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taqui.Models.Cliente", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("DsCPF")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("DS_CPF");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(200)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("DsSenha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar2(200)")
                        .HasColumnName("DS_SENHA");

                    b.Property<string>("DsUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar2(200)")
                        .HasColumnName("DS_USER");

                    b.HasKey("IdUsuario");

                    b.ToTable("T_TAQUI_CLIENTE");
                });
#pragma warning restore 612, 618
        }
    }
}
